const List<String> venueList = [
  "PVR Cinemas, Gachibowli",
  "PVR Cinemas, Shamshabad",
  "PVR Cinemas, Kukatpally",
  "PVR Cinemas, Mallapur",
  "PVR Cinemas, Hi-Tech City",
  "PVR Cinemas, Habsiguda",
  "PVR Cinemas, Habsiguda",
  "PVR Cinemas, Jubilee Hills",
  "PVR Cinemas, Secunderabad",
  "PVR Cinemas, Banjara Hills",
  "PVR Cinemas, Manikonda",
  "PVR Cinemas, Uppal Kalan",
  "PVR Cinemas, Ameerpet",
  "PVR Cinemas, Shamirpet",
  "PVR Cinemas, Sainikpuri",
  "PVR Cinemas, Srinagar Colony",
  "PVR Cinemas, Quthbullapur",
  "PVR Cinemas, A C Guards",
  "PVR Cinemas, AS Roa Nagar",
  "PVR Cinemas, Abids Road",
  "PVR Cinemas, Adarsh Nagar",
  "PVR Cinemas, Adikmet",
  "PVR Cinemas, Afzalgunj",
  "PVR Cinemas, Agapura",
  "PVR Cinemas, Ahmed Nagar",
  "PVR Cinemas, Akbar Road",
  "PVR Cinemas, Alexander Road",
  "PVR Cinemas, Aliabad",
  "PVR Cinemas, Alwal",
  "PVR Cinemas, Amberpet",
  "PVR Cinemas, Anand Bagh",
  "PVR Cinemas, Ashok Nagar",
  "PVR Cinemas, Asif Nagar",
  "PVR Cinemas, Attapur",
  "PVR Cinemas, Attapur Ring Road",
  "PVR Cinemas, Auto Nagar",
  "PVR Cinemas, Azamabad",
  "PVR Cinemas, Azampura Masjid"
];
