const List<String> venueList = [
  "Gachibowli",
  "Shamshabad",
  "Kukatpally",
  "Mallapur",
  "Hi-Tech City",
  "Habsiguda",
  "Habsiguda",
  "Jubilee Hills",
  "Secunderabad",
  "Banjara Hills",
  "Manikonda",
  "Uppal Kalan",
  "Ameerpet",
  "Shamirpet",
  "Sainikpuri",
  "Srinagar Colony",
  "Quthbullapur",
  "A C Guards",
  "AS Roa Nagar",
  "Abids Road",
  "Adarsh Nagar",
  "Adikmet",
  "Afzalgunj",
  "Agapura",
  "Ahmed Nagar",
  "Akbar Road",
  "Alexander Road",
  "Aliabad",
  "Alwal",
  "Amberpet",
  "Anand Bagh",
  "Ashok Nagar",
  "Asif Nagar",
  "Attapur",
  "Attapur Ring Road",
  "Auto Nagar",
  "Azamabad",
  "Azampura Masjid"
];
